Imports System.Collections

Module ErrorCodes
  Public ErrorDescriptions As New Collection

  Public Function GetErrorDescription(ByVal strErrorCode As String) As String
    If ErrorDescriptions.Contains(strErrorCode) Then
      GetErrorDescription = ErrorDescriptions(strErrorCode)
    Else
      GetErrorDescription = "Invalid error code! " & strErrorCode
    End If
  End Function

  Public Sub PopulateErrorDescriptions()
    ' http://www.fincen.gov/forms/files/e-filing_CTRDEPspecs.pdf page 38
    ErrorDescriptions.Add("Non-numeric record counts reported on 1A summary record.", "F01")
    ErrorDescriptions.Add("Number or records reported does not match the computer count for the 2A record or 2A record is not the second record on the file.", "F02")
    ErrorDescriptions.Add("Number of records reported does not match the computer count for the 2B record or 2B record is not the third record on the file.", "F03")
    ErrorDescriptions.Add("Number of records reported does not match the computer count for the 3A record, or 3A is not the fourth record on the file or the 3A record has no corresponding 5A record.", "F04")
    ErrorDescriptions.Add("Number of records reported does not match the computer count 3E records.", "F08")
    ErrorDescriptions.Add("Number of records reported does not match computer count for 4A records.", "F09")
    ErrorDescriptions.Add("Number of records reported does not match computer count for 5A records.", "F10")
    ErrorDescriptions.Add("No Transmitter (1A) Record on file.", "F16")
    ErrorDescriptions.Add("No Branch Summary (9A) Record ofile or a 9A record is found with no prior 3A record.", "F17")
    ErrorDescriptions.Add("No File Summary (9Z) Record on file.", "F18")
    ErrorDescriptions.Add("Branch summary amounts do not equal total of transaction amounts.", "F19")
    ErrorDescriptions.Add("File summary amounts do not equal total of transaction amounts.", "F20")
    ErrorDescriptions.Add("No FI Summary (9B) Record on file.", "F21")
    ErrorDescriptions.Add("FI summary amounts do not equaltotal of transaction amounts.", "F22")
    ErrorDescriptions.Add("Number of records reported does not match computer count for 9E records.", "F23")
    ErrorDescriptions.Add("An invalid record type was present on the submitted file.", "F34")
    ErrorDescriptions.Add("The Transmitter Control Code (TCC) specified in the file is not a valid production TCC code.", "F88")
    ErrorDescriptions.Add("The submitted batch is not a valid version.", "F90")
    ErrorDescriptions.Add("The submitted EBCDIC file is invalid.", "F91")
    ErrorDescriptions.Add("The submitted file is empty or the file type is invalid.", "F92")
    ErrorDescriptions.Add("An invalid line terminator was present on the submitted file", "F93")
    ErrorDescriptions.Add("Cannot continue processing the submitted file because of previous errors encountered.", "F94")
    ErrorDescriptions.Add("Too many errors were encountered while processing the submitted file to continue.", "F95")
    ErrorDescriptions.Add("One, or more, invalid characters were present in the submitted file. ", "F96")
    ErrorDescriptions.Add("Invalid record sequencing was present on the submitted file.", "F97")
    ErrorDescriptions.Add("An invalid record length was present on the submitted file.", "F98")
    ErrorDescriptions.Add("Unknown file error.  Please contact the BSA E-Filing Help Desk for assistance.", "F99")
    ErrorDescriptions.Add("Transmitter Name is blank.", "T01")
    ErrorDescriptions.Add("Transmitter Address is blank.", "T02")
    ErrorDescriptions.Add("Transmitter City is blank.", "T03")
    ErrorDescriptions.Add("Transmitter State is blank.", "T04")
    ErrorDescriptions.Add("Transmitter ZIP Code is blank.", "T05")
    ErrorDescriptions.Add("Transmitter Area Code and/or Telephone Number is blank.", "T06")
    ErrorDescriptions.Add("Transmitter Contact Name is blank.", "T07")
    ErrorDescriptions.Add("Transmitter EIN is blank or invalid.", "T08")
    ErrorDescriptions.Add("Coverage beginning date is blank or invalid.", "T09")
    ErrorDescriptions.Add("Coverage ending date is blank or invalid.", "T10")
    ErrorDescriptions.Add("Coverage ending date is more than 25 days from coverage beginning date. (Information only)", "T11")
    ErrorDescriptions.Add("Transmitter Control Code is blank or invalid.", "T12")
    ErrorDescriptions.Add("FI Name is blank or contains leading spaces.", "001")
    ErrorDescriptions.Add("FI Address is blank.", "002")
    ErrorDescriptions.Add("FI City is blank.", "003")
    ErrorDescriptions.Add("FI State is blank.", "004")
    ErrorDescriptions.Add("FI ZIP Code is blank, zeros, not numeric, or invalid.", "007")
    ErrorDescriptions.Add("FI Federal Regulator or BSA examiner code is blank or invalid.", "008")
    ErrorDescriptions.Add("Name of Approving Official is blank.", "010")
    ErrorDescriptions.Add("Title of Approving Official is blank.", "011")
    ErrorDescriptions.Add("FI EIN/SSN is missing, all zeros, all nines, invalid or non-numeric.", "012")
    ErrorDescriptions.Add("FI Routing Number is non-numeric, blank, or zeros.", "013")
    ErrorDescriptions.Add("FI Resolution Code is invalid or missing.", "014")
    ErrorDescriptions.Add("FI TCC is blank or invalid.", "015")
    ErrorDescriptions.Add("Type of transaction is blank or contains codes other than 1 thru 7.", "021")
    ErrorDescriptions.Add("Cash in or cash out is missing or non-numeric.", "022")
    ErrorDescriptions.Add("Amounts greater than 20 million will generate this error code as information. Please verify the cash in or cash out amount.", "023")
    ErrorDescriptions.Add("Date of transaction is invalid. a. Date not numeric. b. Month not a valid code 01-12. c. Day not a valid code 01-31 d. Date not less than current date.", "024")
    ErrorDescriptions.Add("Contact name is missing.", "025")
    ErrorDescriptions.Add("Contact phone number is missing.", "026")
    ErrorDescriptions.Add("Preparer Name is missing.", "028")
    ErrorDescriptions.Add("Preparer Title is missing.", "029")
    ErrorDescriptions.Add("Number of transactors is not numeric.", "030")
    ErrorDescriptions.Add("Number of transactors is numeric and no Transactor Records are present.", "031")
    ErrorDescriptions.Add("Number of transactors is numeric but the value does not equal the number of Transactor Records present.", "032")
    ErrorDescriptions.Add("Number of owners is not numeric.", "034")
    ErrorDescriptions.Add("Number of owners value does not equal the number of Owner Records present.", "035")
    ErrorDescriptions.Add("Number of Customer Account Records is not numeric.", "036")
    ErrorDescriptions.Add("Number of customer accounts value does not equal the number of Customer Account Records present.", "037")
    ErrorDescriptions.Add("Invalid Document Control Number Returned. (CTR not updated)", "038")
    ErrorDescriptions.Add("Missing Account Number for Transaction types of Deposit or Withdrawal.", "039")
    ErrorDescriptions.Add("Section B Reason Incomplete is all spaces but no Transactor (4A) Record is present.", "040")
    ErrorDescriptions.Add("The Cash In or Cash Out amount(s) is invalid. Only cash transactions that exceed $10,000 should be reported.", "076")
    ErrorDescriptions.Add("The Foreign Currency Country Code field was provided on the Currency Transaction Summary (3A) Record b the Foreign Cash In and the Foreign Cash Out fields are all spaces or are all zeros.", "077")
    ErrorDescriptions.Add("The Foreign Currency Country Code field is all spaces on the Currency Transaction Summary (3A) Record when an amount was provided in the Foreign Cash Out field.", "078")
    ErrorDescriptions.Add("The Foreign Currency Country Code field is all spaces on the Currency Transaction Summary (3A) Record when an amount was provided in the Foreign Cash In field.", "079")
    ErrorDescriptions.Add("Number of customer accounts not numeric.", "083")
    ErrorDescriptions.Add("Number of customer accounts does not match number of accounts listed.", "084")
    ErrorDescriptions.Add("Transactor Name is invalid.", "091")
    ErrorDescriptions.Add("Transactor Number and street is blank.", "092")
    ErrorDescriptions.Add("Transactor City is blank.", "093")
    ErrorDescriptions.Add("Transactor State is blank.", "094")
    ErrorDescriptions.Add("Transactor Country is US, CA or MX but state is not a standard abbreviation. ", "095")
    ErrorDescriptions.Add("Transactor Country is not a valid country abbreviation.", "096")
    ErrorDescriptions.Add("Transactor ZIP Code is blank, zeros, or invalid and the Country is US.", "097")
    ErrorDescriptions.Add("Transactor SSN is spaces, zeros or non-numeric.", "098")
    ErrorDescriptions.Add("Transactor Method of identification is not a valid code.", "100")
    ErrorDescriptions.Add("Transactor Method of identification issued by is not a valid code.", "101")
    ErrorDescriptions.Add("Transactor Address is missing.", "102")
    ErrorDescriptions.Add("Transactor Date of birth is missing or invalid.", "103")
    ErrorDescriptions.Add("Transactor SSN is not valid according to our files.", "104")
    ErrorDescriptions.Add("Transactor SSN does not match our file a valid SSN for the name shown.", "105")
    ErrorDescriptions.Add("Owner Name is invalid. a. Blank. b. Not in proper format. c. Contains no slashes for individual.", "111")
    ErrorDescriptions.Add("Owner Number and street is blank.", "112")
    ErrorDescriptions.Add("Owner City is blank.", "113")
    ErrorDescriptions.Add("Owner State is blank.", "114")
    ErrorDescriptions.Add("Owner Country is US, CA or MX but state is not a standard abbreviation.", "115")
    ErrorDescriptions.Add("Owner Country is not a valid country abbreviation.", "116")
    ErrorDescriptions.Add("Owner ZIP Code is blank, zeros, or invalid and Country code is US.", "117")
    ErrorDescriptions.Add("Owner Identifying number Record is invalid.  Identifying number is zeros, all nines, invalid or non-numeric.", "119")
    ErrorDescriptions.Add("Owner Address contains punctuation.", "122")
    ErrorDescriptions.Add("Owner Alien ID information is missing when EIN/SSN is blank.", "125")
    ErrorDescriptions.Add("Owner Date of birth is missing or invalid.", "126")
    ErrorDescriptions.Add("Owner SSN/EIN is not valid according to our files.", "128")
    ErrorDescriptions.Add("Owner SSN/EIN does not match our file as a valid SSN/EIN for the name shown.", "129")
    ErrorDescriptions.Add("Owner ‘DBA’ name is missing.", "130")
    ErrorDescriptions.Add("Owner ‘DBA’ record is present without an associated owner ‘5A’ record.", "131")
    ErrorDescriptions.Add("The Method of Identification field on the Owner Summary ‘5A’ record has avalue of A, B, C, or D and the ID Issued By field and/or ID Number field is blank.", "150")
    ErrorDescriptions.Add("Type of Transaction is blank or contains code other than A, C, D.", "901")
    ErrorDescriptions.Add("Exemption Status contains codes other than A or B.", "902")
    ErrorDescriptions.Add("Business or Sole Proprietor Name is blank or contains leading spaces.", "903")
    ErrorDescriptions.Add("Exempt Person address is blank ", "904")
    ErrorDescriptions.Add("Exempt Person state is blank ", "905")
    ErrorDescriptions.Add("Exempt Person ZIP Code is blank, non-numeric, or invalid.", "906")
    ErrorDescriptions.Add("Exempt Person TIN is missing, invalid or not numeric.", "907")
    ErrorDescriptions.Add("Exemption Basis is blank or contains codes other than A,B,C,D,E, or F.", "908")
    ErrorDescriptions.Add("Effective date of the exemption is blank or invalid. a. Date not numeric b. Month not 01-12. c. Day not a valid code 01-31.", "909")
    ErrorDescriptions.Add("OBSOLETE", "910")
    ErrorDescriptions.Add("9F record is missing. Must have a 9Frecord for every 9E record.", "911")
    ErrorDescriptions.Add("Approving official name blank. ", "912")
    ErrorDescriptions.Add("Date of Approval (signature) is blank or invalid. a. Date (Not numeric) b. Month not 01-12. c. Day not a valid code 01-31 d. Date is not less than current date.", "913")
    ErrorDescriptions.Add("Contact phone is blank or does not contain 10 numeric characters (3 dig area code and 7 digit number).", "914")
    ErrorDescriptions.Add("Invalid Document Control Number Returned. (CTR not updated)", "917")
    ErrorDescriptions.Add("Contact Name is blank.", "918")
    ErrorDescriptions.Add("Exempt Person TIN is not valid according to our files. Note: Error code 928 is a warning message only.", "928")
    ErrorDescriptions.Add("Exempt Person TIN does not match our file as a valid SSN/TIN for the name shown.  Note: Error code 929 is a warning message only.", "929")
    ErrorDescriptions.Add("Affiliate bank name is blank or contains leading spaces.", "930")
    ErrorDescriptions.Add("Affiliated bank’s address is blank.", "931")
    ErrorDescriptions.Add("Affiliated bank’s state is blank.", "932")
    ErrorDescriptions.Add("Affiliated bank’s ZIP Code is blank, zeros, not numeric or invalid, and the Affiliated bank’s country code is blank or invalid.", "933")
    ErrorDescriptions.Add("Affiliated bank’s TIN is missing, invalid or not numeric.", "934")
    ErrorDescriptions.Add("Affiliated bank’s Federal Regulator isblank or contains codes other than A, B, C, D, E or F.", "935")
    ErrorDescriptions.Add("This submission cannot be Accepted because it contains significant errors.  Please fix and resubmit the file.", "E00")
    ErrorDescriptions.Add("This submission cannot be Accepted because it contains significant errors.  Please fix the file and resubmit or resubmit the same file with the override option applied.", "E01")
    ErrorDescriptions.Add("This submission has been Accepted and will be processed by ECC-M, however it contains some errors which need to be corrected once this submission has been acknowledged.", "E02")
    ErrorDescriptions.Add("This submission had the override option applied and has been Accepted to be processed by ECC-M.  However it contains some errors that need to be corrected once this submission has been acknowledged.", "E03")
    ErrorDescriptions.Add("The override could not be applied because the submission that was specified to be overridden could not be found or is invalid.", "E04")
    ErrorDescriptions.Add("The override could not be applied because the submission that was specified to be overridden is already overridden.", "E05")
    ErrorDescriptions.Add("The override could not be applied because the submission that was specified to be overridden is not in the Rejected state.", "E06")
    ErrorDescriptions.Add("The override could not be applied because the submitted file data has changed, or new/different errors were returned.  Please resubmit the unchanged file, fix the file, or resubmit the same file, with the override applied to this submission.", "E07")
    ErrorDescriptions.Add("The override could not be applied because the version of the submitted file is not valid for the override option.", "E08")
    ErrorDescriptions.Add("The override could not be applied because of errors returned.", "E09")
  End Sub
End Module
